namespace CMCS.Shared.Models;

public enum AlgorithmType
{
    Ethash,
    Etchash,
    Octopus,
    KawPow,
    BeamHashIII,
    NeoScrypt,
    FiroPow,
    ProgPow,
    ProgPowZ,
    Verthash,
    CryptoNightHaven,
    CryptoNightGPU,
    CryptoNightFastV2,
    Cortex,
    kHeavyHash,
    Ubqhash,
    Cuckatoo32,
    CuckooCycle,
    Cuckaroo29s,
    ZelHash,
    Equihash,
    Zhash,
    Autolykos,
    RandomX,
    X25X,
}